name: Deploying snake to EB/Dockerhub

on:
  push:
    branches:
      - 'cicd-eb'

env:
  AWS_REGION: 'eu-west-2'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: cicd-eb
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DHU }}
          password: ${{ secrets.DHT }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: chaseums0967/cicd-eb:latest

  # TODO DO WE NEED A SECOND IMAGE TO DO THIS..?
  eb_deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: cicd-eb
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      -
        name: Install EB CLI
        run: pip install awsebcli --upgrade
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      -
        name: Init Elastic Beanstalk
        run: |
          chmod +x eb-init.sh
          ./eb-init.sh
      -
        name: Create Env / Deploy App
        run: |
          eb create cicd-eb-dev
